### ISSUE TITLE
recoil types

### ISSUE THREAD

**Issue by HenningSE** [XENONnT/epix#14]
Since https://github.com/XENONnT/epix/pull/10 we are using the NEST ID as recoil type identifier. In WFsim theses IDs are mapped to NR, ER or Alpha in https://github.com/XENONnT/WFSim/blob/master/wfsim/core.py#L22. I ran some neutron simulations and got in about 5% of the generated instructions the NEST ID `12`.  This case is used in [epix](https://github.com/XENONnT/epix/blob/master/epix/clustering.py#L271) if the interaction does not match any implemented classification.

**Comment by HenningSE** [comment]
I checked the particle type for the interactions that are later classified with NEST ID `12` and found that they are interactions from positrons.

**Comment by WenzDaniel** [comment]
Thanks a lot. We can change it according to NEST do you make a PR?

**Comment by ramirezdiego** [comment]
Can we leave the issue open to sort this out during validation? Assuming that the fix is to keep ER (e-) by default, as done before https://github.com/XENONnT/epix/pull/10.
