### ISSUE TITLE
Typo in the Kr83m energy (9.4 keV)

### ISSUE THREAD

**Issue by sophiafarrell** [XENONnT/epix#17]
I believe the following energy should be 9.4 keV, not 9.1 keV. I will fix this once I can talk to the experts since this is my first time looking at this.

Also, the comparison for nest to make equal _SHOULD_ be fixed in the upcoming patch, so let's keep this issue open for a couple days in the hopes that NEST versions up soon and we can fix all these issues together. 

https://github.com/XENONnT/epix/blob/e3cc08fc6ccdefbae89ab9e7b5bd58f53726b09c/epix/quanta_generation.py#L45

**Comment by WenzDaniel** [comment]
Hi Sophia, thanks for spotting it. Yes, to me it looks like a bug too. Nice thing to get NEST news first hand ;)

**Comment by HenningSE** [comment]
Hi Sophia, you are right it should be 9.4 keV not 9.1 keV. At the moment it should not make a big difference since `max_allowed_energy_difference` was set to 1 keV but we should definitely change it when the NEST update is live.

**Comment by ramirezdiego** [comment]
Hi all, did we take any action here?
@sophiaandaloro See our current nestpy version:
https://github.com/XENONnT/base_environment/blob/02ef89f809fd8fd77455526249e81983d29ce1a9/requirements.txt#L32

**Comment by sophiaandaloro** [comment]
Hi @ramirezdiego, as of nestpy v1.4.8 this zero-comparison bug should be fixed so we should be good to go to change this to 9.4 keV.

**Comment by sophiaandaloro** [comment]
Hey @HenningSE, should we keep the max_allowed_energy_difference to be 1 keV or would we like to decrease that? I understand that your documentation above is indicating that clustering means we can't get (yet) much more accurate on energy estimation. In this case I will only change the 9.1 to 9.4 but leave the epix-specific 1 keV margin intact.

**Comment by ramirezdiego** [comment]
Solved in https://github.com/XENONnT/epix/pull/30.
