### ISSUE TITLE
module 'awkward' has no attribute 'to_pandas' since awkward version 2.0

### ISSUE THREAD

**Issue by jarongrigat** [XENONnT/epix#74]
The `aw.to_pandas` function was annoyingly replaced with `aw.to_dataframe` in awkward version 2.0. This is used in [clustering.py](https://github.com/XENONnT/epix/blob/849a496b237e5fc0f98581dac1a011543c42b5f1/epix/clustering.py#L12).

**Comment by PavelKavrigin** [comment]
@ramirezdiego @jarongrigat - WFSim simulations fail at OSG now because of this issue. Should we maybe catch AttributeError exception when `to_pandas` and use `to_dataframe` in this case? Or is it better just to fix the version in the requirements?

**Comment by PavelKavrigin** [comment]
Just to clarify - they fail when using `montecarlo:fuse_dev_2023.09`, but not with the `montecarlo:development`.

**Comment by ramirezdiego** [comment]
Hi all, Henning and I were aware of this, but in principle this was not an issue for the official containers, as @PavelKavrigin mentions. This said, it is good dev. practice to avoid this potential issues, so I'd be happy if @jarongrigat can add this line of requirement for epix, or even upgrade the functions to enable compatibility with never awkward versions (althought this needs some testing), and fix also the requirements accordingly.

**Comment by ramirezdiego** [comment]
Fixed in https://github.com/XENONnT/epix/pull/77.
